### ISSUE TITLE
Backlog

### ISSUE THREAD

**Issue by ChakshuGautam** [BharatSahAIyak/autotune#11]
- [x] Move from Personal Supabase to Samagra Supabase
- [ ] API Authentication using Supabase
- [ ] Add Forms Questions to Supabase for Training
- [ ] Link Status updates, hf-repos, and model training eval scores to Supabase
- [ ] Deployment to DO
	- [ ] Dynamic GPU to train models

**Comment by KDwevedi** [comment]
closing this as outdated
@ChakshuGautam lmk if anything here has to be carried over to future plans
