### ISSUE TITLE
Autotune Master Ticket

### ISSUE THREAD

**Issue by ChakshuGautam** [BharatSahAIyak/autotune#23]
# Tasklist
- [ ] API
    - [x] Build an API which allows: 
         - Send prompt
         - Select openAPI model
         - Loops to validate json 
    - [x] Model Management
    - [x] Dataset Management
- [ ] @singhalkarun to add node observability
- [x] Admin (Friday first half)
- [x] Fine Tuning
    - [x] Autotune
    - [x] Manually (PT) - Update datasets and retrain (Autotune UI)
- [x] Deployment
    - [x] Huggingface
    - [x] AI Tools

# References
 - Figma @prtkjakhar 
 - Add the hosted link @prtkjakhar 
 - https://github.com/BharatSahAIyak/autotune/issues/22

**Comment by prtkjakhar** [comment]
Hosted Link: https://autotune.vercel.app/

**Comment by KDwevedi** [comment]
@ChakshuGautam Closing this as more or less completed, improvements will be made continually
Please lmk if you think something important here has been missed out and should be carried over
