### ISSUE TITLE
Allow batch prompts in autotune

### ISSUE THREAD

**Issue by KDwevedi** [BharatSahAIyak/autotune#53]
We want to be able to pass an array of prompts
@sooraj1002 to elaborate:
### Usecase
We can define a template in the config for chunks of a document. then the user can upload an array or chunks or a csv of chunks based on which samples can be generated.

### Changes
Process multiple prompts in the same task, and upload all of the samples generated to HF

### Expected Behaviour
n samples per prompt should be generated and tagged with the prompt used to generate them.

**Comment by sooraj1002** [comment]
@KDwevedi this can be closed.
