### ISSUE TITLE
Training Improvements Master Ticket

### ISSUE THREAD

**Issue by sooraj1002** [BharatSahAIyak/autotune#83]
## Frontend Dependencies
- [x] Share GET for datasets

## Backend
- [ ] #87
- [ ] Create API to get metadata to fill model card - this will be workflow agnostic. Will only take the userId and the task type
- [ ] #89
- [x] #84 @TakshPanchal - TBD by 12/06/24
- [ ] API to see scheduled training tasks - Expose the celery queue
- [ ] API to see all models which have been trained - expose model registry
- [ ] #85 - @singhalkarun to provide an API to share task wise status of GPU usage
- [ ] update training API to allow for scheduled training of model - Schedule it in celery
- [ ] #86
- [ ] #88
- [x] #96

**Comment by KDwevedi** [comment]
NVIDIA Triton: https://github.com/triton-inference-server/server

**Comment by KDwevedi** [comment]
Sooraj 
1. Deployment
2. Model Read

Karan
1. Datasets
  1. Model - [Name] [Task] [Dataset] [Last Tuned] [Last Deployed] [Deploy]
  2. Training Datasets - [Name] [Desc] [Model] [Taks] [Last Update]

**Comment by KDwevedi** [comment]
[ASR] -> [Transliteration] -> [Translation] -> [Intent Classification] -> [NER] [T2S]

**Comment by KDwevedi** [comment]
- E2E for a model Label Studio, Dataset, Model, Deployment Button
- Generating training samples
  - Label Studio Feedback
    - Ask Autotune to generate 5-10 training examples for a given correction  
    - Prompt, Config will have to be part of model config --> workflow
- Video Demo


How to plant wheat?

text_classification
--> Computer Programming
--> Agriculture


How to plant beets?
What is wheat about?
--> Agriculture
--> Agriculture


FE 
1,2 -> Correct
3,4,5 -> Discard

**Comment by KDwevedi** [comment]
closing this ticket as not required, all remaining contextual tasks have been moved to #117, #118
